// Generated by CoffeeScript 1.12.7
(function() {
  var age, degree, emp, employee, firstThreeFood, food, foodArray, foodCpy, gender, i, j, len, len1, name, person, rest, yell;

  name = "Scott";

  person = true;

  age = 33;


  /*
  funciton always returns last line
   */

  yell = function(a) {
    alert(name);
    return alert(a);
  };

  yell(25);


  /*
  conditional operator
   */

  if (person) {
    yell(age);
  }

  if (!person) {
    yell(age);
  }

  if (person) {
    yell(age);
  }

  if (age > 33) {
    yell("age is greated than 33");
  }


  /*
  existentsial operator
   */

  if (typeof gender !== "undefined" && gender !== null) {
    gender = "MALE";
  }

  degree = "";

  if (degree != null) {
    degree = "B.TECH";
  }


  /*
  arrays and objects
   */

  foodArray = ["rice", "veggie", "chicken"];

  employee = {
    name: name,
    age: age,
    welcomeMsg: function() {
      return "Hi " + age;
    },
    perviousOrg: perviousOrg,
    currentOrg: currentOrg,
    techStack: {
      frontEnd: ["JavaScript", "CoffeeScrtp"],
      backEnd: ["C#", "Asp.Net Core"]
    }
  };


  /*
  loop
   */

  for (i = 0, len = foodArray.length; i < len; i++) {
    food = foodArray[i];
    if (food !== "rice") {
      console.log(food);
    }
  }

  for (j = 0, len1 = employee.length; j < len1; j++) {
    emp = employee[j];
    console.log(emp.name);
  }


  /*
  splats
   */


  /*
  array slicing
   */

  firstThreeFood = foodArray.slice(0, 3);

  rest = foodArray.slice(3);

  foodCpy = foodArray.slice(0);

}).call(this);
